config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'sessions/new'
  get 'pages/home'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/events', to: 'dashboard#events'
  get 'dashboard/posts', to: 'dashboard#posts'
  get 'dashboard/prayers', to: 'dashboard#prayers'
  get 'c4c-signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'dashboard/events/new', to: 'dashboard#newEvent', as: 'dashboard_new_event'
  get 'dashboard/events/edit/:id', to: 'dashboard#editEvent', as: 'dashboard_edit_event'

  get 'dashboard/posts/edit/:id', to: 'dashboard#editPost', as: 'dashboard_edit_post'
  get 'dashboard/prayer/:id', to: 'dashboard#viewPrayer', as: 'dashboard_prayer'

  resources :users

  resources :events

  mount RedactorRails::Engine => '/redactor_rails'
  resources :prayers

  root 'pages#home'

end

app/models/event.rb
class Event < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged
  
end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/prayer.rb
class Prayer < ActiveRecord::Base
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	def admin?
		self.role == 'admin' 
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def require_user
  	redirect_to root_url unless current_user
  end

  def require_admin
  	redirect_to root_url unless current_user.admin?
  end



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_action :require_user

  def index
  	@recent_events = Event.all
  end

  def events
  	@events = Event.all
  end

  def posts
  	@posts = Post.all
  end

  def newEvent
    @event = Event.new
  end

  def editEvent
    @event = Event.find(params[:id])
		@upcoming_events = Event.all
  end

	def editPost
		@post = Post.find(params[:id])
	end

	def prayers
		@prayers = Prayer.order('created_at desc')
	end

	def viewPrayer
		@prayer = Prayer.find(params[:id])
	end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def create
  	@event = Event.create(event_params)
    if @event.save
      redirect_to dashboard_events_path
    else
      redirect_to dashboard_new_event_path
    end
  end

  def show
    @event = Event.friendly.find(params[:id])
  end

  def update
    @event = Event.friendly.find(params[:id])
    if @event.update(event_params)
      redirect_to dashboard_events_path
    end
  end

  def destroy
  	@event = Event.friendly.find(params[:id])
  	@event.destroy
  	redirect_to dashboard_events_path
  end


  private
    def event_params
      params.require(:event).permit(:title, :date, :description, :start_date, :end_date, :slug)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @upcoming_events = Event.all
    @posts = Post.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to dashboard_posts_path
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update(post_params)
      redirect_to dashboard_posts_path
    end
  end

  def destroy
  	@post = Post.friendly.find(params[:id])
  	@post.destroy
  	redirect_to dashboard_posts_path
  end


  private
    def post_params
      params.require(:post).permit(:title, :pub_date, :end_date, :body, :slug)
    end

end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController

  def create
    @prayer = Prayer.new(prayer_params)
    if @prayer.save
      PrayerMailer.prayer_request(@prayer).deliver
      PrayerMailer.prayer_request_received(@prayer).deliver
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    @prayer = Prayer.find(params[:id])
    @prayer.destroy
    redirect_to dashboard_prayers_path
  end

  private
    def prayer_params
      params.require(:prayer).permit(:full_name, :email, :phone, :prayer_request)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	puts params[:email]
  	user = User.find_by_email(params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		session[:user_id] = user.id
  		redirect_to root_url
  	else
  		redirect_to login_url
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url
		else
			redirect_to signup_url
		end
	end

	private

		def user_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_dashnav.html.erb
<div class="dash-navbar-container">
	<nav class="navbar navbar-dash">
  	<div class="container">
  	  <!-- Brand and toggle get grouped for better mobile display -->
  	  <div class="navbar-header">
  	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 	data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
  	      <span class="sr-only">Toggle navigation</span>
  	      <span class="icon-bar"></span>
  	      <span class="icon-bar"></span>
  	      <span class="icon-bar"></span>
  	    </button>
  	    <a class="navbar-brand" href="/dashboard">Dashboard</a>
  	  </div>

  	  <!-- Collect the nav links, forms, and other content for toggling -->
  	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  	    <ul class="nav navbar-nav">
  	      <li><a href="/dashboard/events">Events</a></li>
          <li><a href="/dashboard/posts">Announcements</a></li>
					<li><a href="/dashboard/prayers">Prayers</a></li>
          <li><a href="/">View Site</a></li>


  	    </ul>

  	    <ul class="nav navbar-nav navbar-right">
  	      <li><%= link_to "Logout", logout_path, method: :delete %></a></li>

  	    </ul>
  	  </div><!-- /.navbar-collapse -->
  	</div><!-- /.container-fluid -->
	</nav>
</div>

app/views/dashboard/editEvent.html.erb
<%= render 'dashnav' %>

<div class="container">
	<div class="row">
		<div class="col-md-9">
			<h2 class="latoblack underline">Edit Event</h2>
			<%= form_for @event, url: {controller: "events", action: "update"} do |f| %>
				<div class="form-group">
					<label>Title</label>
					<%= f.text_field :title, class: "form-control latolight", placeholder: "Event Title" %>
				</div>
				<div class="form-group" id="date_picker">
					<label>Start Date</label>
					<%= f.text_field :start_date, class: "form-control latolight", placeholder: "Event Start Date" %>
				</div>
				<div class="form-group" id="date_picker2">
					<label>End Date</label>
					<%= f.text_field :end_date, class: "form-control latolight", placeholder: "Event End Date" %>
				</div>
				<div class="form-group">
					<label>Description</label>
					<%= f.text_area :description, class: "form-control redactor" %>
				</div>
				<%= f.submit "Update Event", class: "btn btn-orange" %>
			<% end %>
		</div>
		<!--<div class="col-md-offset-1 col-md-4">
			<h2 class="latoblack underline">Upcoming Events</h2>

		</div>-->
	</div>
</div>

app/views/dashboard/editPost.html.erb
<%= render 'dashnav' %>

<div class="container">
	<div class="row">
		<div class="col-md-9">
			<h2 class="latoblack underline">Edit Post</h2>
      <%= form_for @post, { controller: "posts", action: "update"} do |f| %>
      <div class="form-group">
        <label class="sr-only">Title</label>
        <%= f.text_field :title, class: "form-control latolight", placeholder: "Post Title" %>
      </div>
      <div class="form-group" id="date_picker">
        <label class="sr-only">Publish On Date</label>
        <%= f.text_field :pub_date, class: "form-control latolight", placeholder: "Publish On Date" %>
      </div>
      <div class="form-group" id="date_picker2">
        <label class="sr-only">End Date</label>
        <%= f.text_field :end_date, class: "form-control latolight", placeholder: "Event End Date" %>
      </div>
      <div class="form-group">
        <label class="sr-only">Body</label>
        <%= f.text_area :body, class: "form-control redactor" %>
      </div>
      <%= f.submit "Update Post", class: "btn btn-orange" %>
      
    <% end %>
		</div>
		<!--<div class="col-md-offset-1 col-md-4">
			<h2 class="latoblack underline">Upcoming Events</h2>

		</div>-->
	</div>
</div>

app/views/dashboard/events.html.erb
<%= render 'dashnav' %>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="latoblack underline">Events <span class="pull-right btn btn-orange" data-toggle="modal" data-target="#eventModal"><span class="glyphicon glyphicon-plus latoblack" aria-hidden="true"></span></span></h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<% if @events.present? %>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Title</th>
						<th>Date(s)</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<% for event in @events %>
					<tr>
						<td><p class="latobold"><%= event.title %></p></td>

						<td>

							<% if event.end_date.blank? %>
              <p class="latobold"><%= event.start_date.strftime('%B %-d') %></p>
              <% elsif event.end_date.present? && event.start_date.strftime('%B') === event.end_date.strftime('%B') %>
              <p class="latobold"><%= event.start_date.strftime('%B %-d') %> - <%= event.end_date.strftime('%-d') %></p>
              <% elsif event.end_date.present? && event.start_date.strftime('%B') != event.end_date.strftime('%B') %>
              <p class="latobold"><%= event.start_date.strftime('%B %-d') %> - <%= event.end_date.strftime('%B %-d') %></p>
            <% end %>
						</td>

						<td>
							<p class="latobold text-right">
								<%= link_to "Edit", dashboard_edit_event_path(event) %> |
								<%= link_to "Delete", event, method: :delete %>
							</p>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<% else %>
				<h3 class="latolight">No events scheduled. <a href="" class="orange-link" data-toggle="modal" data-target="#eventModal">Create One</a>.</h3>
			<% end %>
		</div>
	</div>



<!-- Modal -->
<div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title latolight" id="myModalLabel">Create New Event</h3>
      </div>
      <div class="modal-body">
        <%= form_for Event.new do |f| %>
				<div class="form-group">
					<label class="sr-only">Title</label>
					<%= f.text_field :title, class: "form-control latolight", placeholder: "Event Title" %>
				</div>
				<div class="form-group" id="date_picker">
					<label class="sr-only">Date</label>
					<%= f.text_field :start_date, class: "form-control latolight", placeholder: "Event Start Date" %>
				</div>
				<div class="form-group" id="date_picker2">
					<label class="sr-only">Date</label>
					<%= f.text_field :end_date, class: "form-control latolight", placeholder: "Event End Date" %>
				</div>
				<div class="form-group">
					<label class="sr-only">Description</label>
					<%= f.text_area :description, class: "form-control redactor" %>
				</div>
				<%= f.submit "Create Event", class: "btn btn-orange" %>
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<% end %>
      </div>
      <!--<div class="modal-footer">

        <button type="button" class="btn btn-primary">Save changes</button>
      </div>-->
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= render 'dashnav' %>

<div class="container">
	<div class="row">
		<div class="col-md-12">

		</div>
	</div>
</div>

app/views/dashboard/newEvent.html.erb
<%= render 'dashnav' %>
<div class="dash-pg-container">

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="latolight new-event-hdr">Add New Event</h2>
		</div>
	</div>
	<div class="row">
		
		<%= form_for Event.new do |f| %>
		<div class="col-md-8">
			<div class="form-group" id="eventTitle">
				<label class="sr-only">Title</label>
				<%= f.text_field :title, class: "form-control", placeholder: "Event Title" %>
			</div>
			<div class="form-group">
				<label class="sr-only">Description</label>
				<%= f.text_area :description, class: "form-control redactor", placeholder: "Add event details..." %>
			</div>
		</div>
		<div class="col-md-4">
			<div class="form-group start_end_date" id="date_picker">
				<label class="sr-only">Event Start</label>
				<%= f.text_field :start_date, class: "form-control", placeholder: "Start Date" %>
			</div>
			<div class="form-group start_end_date" id="date_picker2">
				<label class="sr-only">Event Ending</label>
				<%= f.text_field :end_date, class: "form-control", placeholder: "End Date" %>
			</div>
		</div>
		
		


	</div>
	<div class="row">
		<div class="col-md-12">
			<%= f.submit "Add Event", class: "btn btn-orange" %>
		</div>
	</div>

	<% end %>
</div>

</div>

app/views/dashboard/posts.html.erb
<%= render 'dashnav' %>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="latoblack underline">Announcements <span class="pull-right btn btn-orange" data-toggle="modal" data-target="#postModal"><span class="glyphicon glyphicon-plus latobold" aria-hidden="true"></span></span></h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<% if @posts.present? %>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Title</th>
						<th>Publish Date</th>
						<th>End Date</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<% for post in @posts %>
					<tr>
						<td><p class="latobold"><%= post.title %></p></td>
						<td><p class="latobold"><%= post.pub_date.strftime('%B %-d, %Y') %></p></td>
						<td><p class="latobold"><% unless post.end_date.blank? %><%= post.end_date.strftime('%B %-d, %Y') %><% end %></p></td>
						<td>
							<p class="latobold text-right">
								<%= link_to "Edit", dashboard_edit_post_path(post) %> |
								<%= link_to "Delete", post, method: :delete %>
							</p>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<% else %>
				<h3 class="latolight">No announcements published. <a href="" class="orange-link" data-toggle="modal" data-target="#postModal">Create One</a>.</h3>
			<% end %>
		</div>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="postModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title latolight" id="myModalLabel">Create New Event</h3>
      </div>
      <div class="modal-body">
        <%= form_for Post.new do |f| %>
				<div class="form-group">
					<label class="sr-only">Title</label>
					<%= f.text_field :title, class: "form-control latolight", placeholder: "Post Title" %>
				</div>
				<div class="form-group" id="date_picker">
					<label class="sr-only">Publish On Date</label>
					<%= f.text_field :pub_date, class: "form-control latolight", placeholder: "Publish On Date" %>
				</div>
				<div class="form-group" id="date_picker2">
					<label class="sr-only">End Date</label>
					<%= f.text_field :end_date, class: "form-control latolight", placeholder: "Event End Date" %>
				</div>
				<div class="form-group">
					<label class="sr-only">Body</label>
					<%= f.text_area :body, class: "form-control redactor" %>
				</div>
				<%= f.submit "Create Post", class: "btn btn-orange" %>
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<% end %>
      </div>
      <!--<div class="modal-footer">

        <button type="button" class="btn btn-primary">Save changes</button>
      </div>-->
    </div>
  </div>
</div>

app/views/dashboard/prayers.html.erb
<%= render 'dashnav' %>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="latoblack underline">Prayer Requests</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<% if @prayers.present? %>
			<table class="table table-striped table-condensed">
				<thead>
					<tr>
						<th>Name</th>
						<th>Email</th>
            <th>Phone</th>
            <th>Received</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					<% for prayer in @prayers %>
					<tr>
						<td><p class="latobold"><%= prayer.full_name %></p></td>

						<td><p class="latobold"><%= prayer.email %></p></td>
            <td><p class="latobold"><%= prayer.phone %></p></td>
            <td><p class="latobold"><%= prayer.created_at.strftime('%B %-d, %Y') %></p></td>

						<td>
							<p class="latobold text-right">
								<%= link_to "View", dashboard_prayer_path(prayer) %> |
								<%= link_to "Delete", prayer, method: :delete %>
							</p>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<% else %>
				<h3 class="latolight">No prayer requests received.</h3>
			<% end %>
		</div>
	</div>
  

app/views/dashboard/viewPrayer.html.erb
<%= render 'dashnav' %>
<div class="container">
	<div class="row">
		<div class="col-md-9">
			<h2 class="latoblack underline">Prayer Request <span class="small latolight">received <%= @prayer.created_at.strftime('%B %-d, %Y') %></span></h2>
      <h3 class="latoblack">Name: <span class="latolight"><%= @prayer.full_name %></span></h3>
      <h3 class="latoblack">Email: <span class="latolight"><%= @prayer.email %></span></h3>
      <h3 class="latoblack">Phone: <span class="latolight"><%= @prayer.phone %></span></h3>
      <h3 class="latoblack">Prayer Request: <span class="latolight"><%= @prayer.prayer_request %></span></h3>
		</div>
		<!--<div class="col-md-offset-1 col-md-4">
			<h2 class="latoblack underline">Upcoming Events</h2>

		</div>-->
	</div>
</div>